import { Inter } from 'next/font/google'
import './globals.css'
import Cabecalho from '@/components/Cabecalho/Cabecalho'
import Body from '@/components/Body/Body'
import Rodape from '@/components/Rodape/Rodape'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by GameCoderGab',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        
        <Cabecalho/>

        <Body/>
        
        {/* {children} */}
        
        <Rodape/>
        </body>
    </html>
  )
}
